export const unaryOp = {
  '-': 'INV',
  '+': 'PLU',
  '!': 'LNOT',
  '~': 'NOT',
  typeof: 'TYPEOF',
  void: 'VOID',
};

export const binaryOp = {
  '==': 'CEQ',
  '!=': 'CNEQ',
  '===': 'CID',
  '!==': 'CNID',
  '<': 'LT',
  '<=': 'LTE',
  '>': 'GT',
  '>=': 'GTE',
  '<<': 'SHL',
  '>>': 'SAR',
  '>>>': 'SHR',
  '+': 'ADD',
  '-': 'SUB',
  '*': 'MUL',
  '/': 'DIV',
  '%': 'MOD',
  '|': 'OR',
  '&': 'AND',
  '^': 'XOR',
  '**': 'EXP',
  in: 'IN',
  instanceof: 'INSTANCEOF',
};

export const assignOp = {
  '+=': 'ADD',
  '-=': 'SUB',
  '*=': 'MUL',
  '/=': 'DIV',
  '%=': 'MOD',
  '<<=': 'SHL',
  '>>=': 'SAR',
  '>>>=': 'SHR',
  '**=': 'EXP',
  '|=': 'OR',
  '&=': 'AND',
  '^=': 'XOR',
};
