name: build
on:
  push:
    branches:
      - master
      - deploy
      - v1
    tags:
      - v1
    paths:
      - 'src/**'
      - '__tests__/**'
      - '.github/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: pnpm install
        run: |
          npm i -g pnpm@8.15.9
          pnpm install --registry=https://registry.npmjs.org
          npm run build
        env:
          CI: true
